
import random
from typing import Generator


def new_coin_flip_bool() -> bool:
    return random.choice([True, False])


def generate_first_names(count: int = 1) -> Generator[str, None, None]:
    first_names = (
        "Aygol",
        "Ragnvald",
        "Krastio",
        "Loïc",
        "Thaleia",
        "Borislava",
        "Iria",
        "Ilithyia",
        "Josu",
        "Goyathlay",
        "Ashur-Bani,-Apli"
        "Shailaja",
        "Haruna",
        "Nadiye",
        "Tadesse",
        "Miltiades",
        "Kynaston",
        "Dinesh",
        "Jenna",
        "Ingólfr",
        "Maximiliana",
        "Amaterasu",
        "Suzana",
        "Dom",
        "Darshan",
        "Cierra",
        "Chetan",
        "Florentina",
        "Annag",
        "Benedek",
        "Georgina",
        "Kory",
        "Sasha",
        "Dionne",
        "Darrick",
        "Joni",
        "Frankie",
        "Leann",
        "Porter",
        "Dewayne",
        "Dorothea",
        "Erica",
        "Violet",
        "Viola",
        "Bridgett",
        "Phyllis",
        "Dona",
        "Erna",
        "Sonja",
        "Rita",
        "Richard",
        "Alvin",
        "Rosetta",
        "Chance",
        "Alice",
        "Rey",
        "Ruby",
        "Erin",
        "Brett",
        "Lakisha",
        "Laurie",
        "Rosario",
        "Marylou",
        "Evan",
        "Len",
        "Clara",
        "Lolita",
        "Kendrick",
        "Cedrick",
        "Nicole",
        "Rubin",
        "Linda",
        "Harold",
        "Jeff",
        "Carey",
        "Lesley",
        "Edward",
        "Sheena",
        "Suzette",
    )
    while True:
        yield from sorted(first_names, key=lambda v: random.random())


def generate_last_names(count: int = 1) -> Generator[str, None, None]:
    last_names = (
        "Briggs",
        "Walter",
        "Sheppard",
        "Caldwell",
        "Randall",
        "Roach",
        "Cannon",
        "Ashley",
        "Lopez",
        "Preston",
        "Olsen",
        "Bruce",
        "Pope",
        "Savage",
        "Lucero",
        "Crosby",
        "Bird",
        "Ruiz",
        "Hamilton",
        "Zimmerman",
        "Abbott",
        "Benjamin",
        "Cisneros",
        "Shannon",
        "Barrett",
        "Vang",
        "Jarvis",
        "Hall",
        "Hughes",
        "Duarte",
        "Fischer",
        "Guerrero",
        "Hayes",
        "Stephenson",
        "Carson",
        "Ramirez",
        "Mullins",
        "Shea",
        "Avila",
        "Palmer",
        "Velazquez",
        "Melton",
        "Robinson",
        "Andrade",
        "Zavala",
        "English",
        "Willis",
        "Carey",
        "Van",
        "Horn",
        "Vargas",
        "Ochoa",
        "Newton",
        "Blanchard",
        "Burns",
        "Vance",
        "Bright",
        "Combs",
        "Cox",
        "Leonard",
        "Hicks",
        "Davies",
        "Keith",
        "Hansen",
        "Phillips",
        "Rodgers",
        "Roman",
        "Johnston",
        "Nelson",
        "Rivas",
        "Hall",
        "Bowen",
        "Benton",
        "Craig",
        "Horne",
        "Mccarty",
        "Wallace",
        "Cantrell",
        "Taylor",
        "Carey",
        "Dudley",
        "Horton",
        "Vasquez",
        "Welch",
        "Martin",
        "Moses",
        "Levine",
        "Castillo",
        "Massey",
        "Peters",
        "Guerra",
        "Murillo",
        "Dorsey",
        "Duran",
        "Rivera",
        "Chandler",
        "Solis",
        "Gilbert",
        "Mathis",
        "Mccoy",
    )
    while True:
        yield from sorted(last_names, key=lambda v: random.random())

def new_email_provider() -> str:
    return random.choice([
        'derpmail.com',
        'foobar.com',
        'mail.net',
        'herp-mail.net',
        'ez-email.com',
        'webmail.org',
        'inbox.com',
    ])

def new_email_address(first_name: str, last_name: str) -> str:
    provider = new_email_provider()
    delim = random.choice([".", "-", "_"])
    value = random.random()
    if value < 0.25:
        return f"{last_name.lower()}{random.randint(1, 99)}@{provider}"
    elif value < 0.50:
        return f"{first_name.lower()[0]}{delim}{last_name.lower()}@{provider}"
    elif value < 0.75:
        return f"{first_name.lower()}{delim}{last_name.lower()}@{provider}"
    else:
        return f"{first_name.lower()[:random.randint(1, 4)]}{delim}{last_name.lower()}@{provider}"

def generate_pet_names(count: int = 1) -> Generator[str, None, None]:
    animal_names = (
        "Abigail",
        "Ace",
        "Adam",
        "Addie",
        "Admiral",
        "Aggie",
        "Aires",
        "Aj",
        "Ajax",
        "Aldo",
        "Alex",
        "Alexus",
        "Alf",
        "Alfie",
        "Allie",
        "Apollo",
        "April",
        "Archie",
        "Argus",
        "Aries",
        "Armanti",
        "Arnie",
        "Arrow",
        "Ashes",
        "Ashley",
        "Astro",
        "Athena",
        "Atlas",
        "Bacchus",
        "Bailey",
        "Bambi",
        "Bandit",
        "Banjo",
        "Barbie",
        "Barclay",
        "Barker",
        "Barkley",
        "Barley",
        "Barnaby",
        "Barney",
        "Baron",
        "Bart",
        "Basil",
        "Baxter",
        "Bb",
        "Beamer",
        "Beanie",
        "Beans",
        "Bear",
        "Ben",
        "Benji",
        "Benny",
        "Benson",
        "Bentley",
        "Bernie",
        "Bessie",
        "Biablo",
        "Bibbles",
        "Biggie",
        "Billie",
        "Billy",
        "Bingo",
        "Binky",
        "Birdie",
        "Birdy",
        "Biscuit",
        "Bishop",
        "Hamlet",
        "Hammer",
        "Hank",
        "Hanna",
        "Hannah",
        "Hans",
        "Happy",
        "Hardy",
        "Harley",
        "Harpo",
        "Harrison",
        "Harry",
        "Harvey",
        "Heather",
        "Heidi",
        "Henry",
        "Hercules",
        "Hershey",
        "Hugh",
        "Hugo",
        "Humphrey",
        "Hunter",
        "India",
        "Indy",
        "Iris",
        "Isabella",
        "Isabelle",
        "Itsy",
        "Itsy-bitsy",
        "Ivory",
        "Ivy",
        "Izzy",
        "Jaguar",
        "Jake",
        "Jamie",
        "Jasmine",
        "Jasper",
        "Jaxson",
        "Jazmie",
        "Jazz",
        "Jelly",
        "Jenna",
        "Jenny",
        "Jerry",
        "Jersey",
        "Jess",
        "Jesse",
        "Jessie",
        "Jester",
        "Jet",
        "Jethro",
        "Jimmy",
        "Jingles",
        "JJ",
        "Joe",
        "Joey",
        "Johnny",
        "Jojo",
        "Joker",
        "Jolie",
        "Jolly",
        "Jordan",
        "Josie",
        "Joy",
        "JR",
        "Judy",
        "Julius",
        "June",
        "Mitzi",
        "Mitzy",
        "Mo",
        "Mocha",
        "Mollie",
        "Nala",
        "Nana",
        "Natasha",
        "Nellie",
        "Nemo",
        "Nena",
        "Peanut",
        "Peanuts",
        "Pearl",
        "Pebbles",
        "Penny",
        "Phoebe",
        "Phoenix",
        "Sara",
        "Shasta",
        "Sheba",
        "Sheena",
        "Shelby",
        "Shelly",
        "Sienna",
        "Sky",
        "Skye",
        "Weaver",
        "Webster",
        "Wesley",
        "Westie",
    )
    while True:
        yield from sorted(animal_names, key=lambda v: random.random())
